version: "3.5"

services:
  admin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db:${MYSQL_HOST}
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_HOST: ${MYSQL_HOST}
      PMA_PORT: ${MYSQL_PORT}

  db:
    image: mysql:8
    restart: always
    container_name: ${MYSQL_HOST}
    cap_add:
      - SYS_NICE
    volumes:
      - ./database/data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    environment:
      MYSQL_TCP_PORT: ${MYSQL_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}

  backend:
    container_name: nestjs_api_dev
    image: nestjs-api-dev:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:debug
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - db